### ISSUE TITLE
An algorithms/interview skills workshop in San Francisco

### ISSUE THREAD

**Issue by akanshmurthy** [railsbridge/organizing#101]
Following with the experimentation (after the recent test-driven workshop) of different events, another idea that came up was a workshop focused on algorithms and behavior questions that could help RailsBridge folks who are job searching. This would be less formalized than the typical workshops but could still be structured: 

- intro before the start of the day: explain how technical interviews are held and certain approaches/systems of thought that can be helpful
- morning session: pick out most common algorithm questions, pair up, do a problem each in a certain amount of time, and then have an organizer explain solutions
- afternoon session: pick out most common behavioral questions, pair up, ask a question each in a certain amount of time, and then have an organizer explain ways to answer the question

Thoughts?

CC: @schaui6 @aneyzberg

**Comment by tigarcia** [comment]
I think it's a great idea.  It would be a good idea to have different levels of problems.  I'm happy to help with curriculum creation.  I have interviewed quite a few candidates in past jobs.

**Comment by akanshmurthy** [comment]
Thanks! If we want to do this in December, could we use your space? We might try to see how it goes and create official curricula after the event.

**Comment by schaui6** [comment]
@akanshmurthy I'm talking to Dan from Outco and he has expressed interesting in sponsoring, I'm just waiting on a confirmation.

**Comment by akanshmurthy** [comment]
Hey, @tigarcia and @schaui6 , the need for an algorithms curriculum came up again recently (it was explicitly suggested by a student). If y'all are interested, we can form a group and do this!
