### ISSUE TITLE
South Bay Front End Workshop - Date TBD

### ISSUE THREAD

**Issue by rachelmyers** [railsbridge/organizing#16]
Hi guys! We haven't had a workshop in the south bay in a while. Should we do this thing!? I don't know who's available to do this, so I'll just start cc-ing people. :smile_cat:

**Comment by ruchikakumar** [comment]
Hey guys, I'm going to close this out.  Lets start another issue if someone wants to organize a south bay workshop and had identified a venue.  Thanks!
