### ISSUE TITLE
Phoenix, AZ Rails workshop

### ISSUE THREAD

**Issue by rachelmyers** [railsbridge/organizing#38]
A few months out:
- [x] Find a venue and sponsor for the workshop. (The costs of sponsoring the workshop depend on the RSVP limit; it's mostly food; it's usually between $600 and $1000.)
- [x] Find two to four co-organizers. It's a lot of work, but always a lot of fun. No experience necessary; checkout the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook) if it's new to you. (Also, we match up first time organizers with mentors.) 
  - @brobertsaz I think is open to organizing
  - who else??

Just leave a comment below if you're able to organize! :smile_cat: 

Once we have a venue/sponsor and organizers, we can:
- [x] Set an RSVP limit that works for everyone
- [x] Post the workshop to [Bridge Troll](http://www.bridgetroll.org/)
- [ ] Post the workshop to local user group calendars. 

One to two weeks out, we can:
- [ ] Plan a teacher training
- [ ] Order breakfast
- [ ] Order lunch
- [ ] Find a good place for the afterparty

After the workshop, we can:
- [ ] Party! :high_brightness:  
- [ ] Have a teacher retrospective
- [ ] Have a student retrospective
- [ ] Have an organizer retrospective
- [ ] Post all the feedback to the mailing list, so we'll all benefit!

**Comment by ruchikakumar** [comment]
Hey guys, closing the issue out.  I hope the event was a success, we love hearing feedback.
