### ISSUE TITLE
Green Bay Frontend Workshop - Need Date/Location

### ISSUE THREAD

**Issue by GeekOnCoffee** [railsbridge/organizing#39]
In the early stages of planning, but interest is high from the community, have a couple of potential venues in mind, just need to make contact and come up with a date.

**Comment by ruchikakumar** [comment]
Hi @GeekOnCoffee I'm closing this issue out. Lets reopen a new one if this is sill of interest, thanks!  If you still need a mento cc @aneyzberg .   Thank you.
