### ISSUE TITLE
Burlington, Vermont Workshop (date TBD)

### ISSUE THREAD

**Issue by alexch** [railsbridge/organizing#40]
@alexch @dangeranger @ktoksu are planning on planning a Vermont workshop this fall (or maybe winter)

Here's what we need to do!

A few months out:
- [ ] Decide on topics: Frontend or Ruby on Rails ?
- [ ] Find a venue and sponsor for the workshop. Sponsoring the workshop costs between $400 and $900, depending on the size of the workshop.
- [ ] Sign up on the [organizers email list](https://github.com/railsbridge/docs/wiki/Cookbook)
  - [x] @alexch 
  - [ ] @dangeranger
  - [ ] @ktoksu 
- [ ] Read through the entire [workshop cookbook](https://groups.google.com/forum/#!forum/railsbridge-workshop) and [organizing readme](https://github.com/railsbridge/organizing)
  - [ ] @alexch 
  - [ ] @dangeranger
  - [ ] @ktoksu 
- [ ] Find a mentor via the organizers mailing list

Leave a comment below if you're able to host, sponsor or organize! :smile_cat: 

Once we have a a venue, sponsors, and organizers, we can:
- [ ] Work together to set an RSVP limit that works for everyone
- [ ] Post the workshop to [Bridge Troll](http://www.bridgetroll.org/)
- [ ] Post the workshop to [Meetup](http://www.meetup.com/sfruby/#calendar) for publicity 
- [ ] Coordinate with Mo (Girl Develop It BTV)

One to two weeks out, we can:
- [ ] Plan a teacher training
- [ ] Order breakfast
- [ ] Order lunch
- [ ] Find a good place for the afterparty

After the workshop, we can:
- [ ] Party! :tada:   
- [ ] Retro

:tulip:

**Comment by ruchikakumar** [comment]
HI @Dangeranger I'm closing this issue out.  Please reach out to myself @aneyzberg (SF railsbridge temporary leads) if you have any questions.  Thanks.

**Comment by rachelmyers** [comment]
@alexch, @mmcelaney, and @Dangeranger: We didn't meant to step on any toes here. @ruchikakumar is closing out old and stale issues, but if you guys are still working on this, please reopen this one! :smile_cat:
