### ISSUE TITLE
2015 SF Rails Workshop for Women at Engine Yard

### ISSUE THREAD

**Issue by rachelmyers** [railsbridge/organizing#41]
#### The good folks at Engine Yard :steam_locomotive:, especially @alenia, :ok_woman:  got in touch and are making this happen! 

Here's a giant list of TODOs, this time with extra emoji! :tulip: 

A few months out:
- [x] Find a venue and sponsor for the workshop: I think EngineYard's :steam_locomotive: interested in hosting this; we can confirm
- [x] Find co-organizers and start going through the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook): @shanaclaire, @alenia, and @michelleN from Engine Yard :steam_locomotive: 

Once we have a venue/sponsor and organizers, we can:
- [ ] Set a date :calendar:  that works for everyone. (Late October or Early November looks good) :fallen_leaf: 
- [ ] Set an RSVP limit :two_women_holding_hands::two_women_holding_hands::two_women_holding_hands::two_women_holding_hands: that works for everyone
- [ ] Post the workshop to [Bridge Troll](http://www.bridgetroll.org/) :pushpin: 
- [ ] Post the workshop to [Meetup](http://www.meetup.com/sfruby/#calendar) if we don't get enough volunteers from BridgeTroll alone. :traffic_light: 

One to two weeks out, we can:
- [ ] Plan a teacher training :books:, preferably at Engine Yard :steam_locomotive:, but maybe somewhere else
- [ ] Order breakfast :coffee: 
- [ ] Order lunch :hamburger: 
- [ ] Find a good place for the afterparty :tropical_drink: 

After the workshop, we can:
- [ ] Party! :tada:
- [ ] Retro :dress: 
- [ ] [Expense](https://atrium.schoolfactory.org/bridgefoundry/node/108690) :moneybag: anything that EngineYard :steam_locomotive: doesn't cover

**Comment by shanaclaire** [comment]
Hi @ruchikakumar Let's plan on March 14th. Would this include Friday, March 13th as well?

Thanks!

**Comment by celestelayne** [comment]
@shanaclaire, we actually have space in February (20th/21st) to do an RoR workshop. It does include a Friday evening 2-hour installfest. Would this still work for you?

**Comment by celestelayne** [comment]
@shanaclaire if February doesn't work, we would love to do March 13th/14th

**Comment by ruchikakumar** [comment]
Hi @shanaclaire , yes typically it includes Friday. Are you set for March?!

**Comment by shanaclaire** [comment]
Hi @celestelayne and @ruchikakumar I'm currently checking on the February date and I'll let you know early next week. It doesn't look like March will work for us though. Thank you!

**Comment by celestelayne** [comment]
ok, thanks @shanaclaire looking forward to it.

**Comment by lilliealbert** [comment]
Closing this issue — if Engine Yard wants to host a workshop in the future, they should totally get in touch with the SF leadership team at SF@railsbridge.org and see what we can work out!

:panda_face:
