### ISSUE TITLE
PDX Workshop

### ISSUE THREAD

**Issue by amypivo** [railsbridge/organizing#42]
I'm moving from SF to Portland and bringing railsbridge with me! I'm uncertain if we should attempt hosting a workshop this close to the holiday season or start fresh in January. 

A few months out:

- [x] Find a venue and sponsor for the workshop: ThoughtWorks can help sponsor. 
- [x] Find co-organizers and start going through the workshop cookbook. 
- [ ] Start creating a list of contacts in Portland!

Once we have a venue/sponsor and organizers, we can:
- [x] Set a date  that works for everyone. (
- [ ] Set an RSVP limit- this wil depend on the venue. 
- [ ] Post the workshop to [Bridge Troll](http://www.bridgetroll.org/)
- [ ] Post the workshop to [Meetup](http://www.meetup.com/sfruby/#calendar) for publicity 

One to two weeks out, we can:
- [ ] Plan a teacher training 
- [ ] Order breakfast
- [ ] Order lunch 
- [ ] Find a good place for the afterparty

After the workshop, we can:
- [ ] Party! 
- [ ] Retro 
- [ ] Expense anything we can't get sponsors to cover!

**Comment by ruchikakumar** [comment]
Hey @amypivo just checking that I'm OK to close this issue out? How was the event?
