### ISSUE TITLE
SF  January 30 & 31 Rails Workshop for Women at Blurb

### ISSUE THREAD

**Issue by danigro77** [railsbridge/organizing#43]
#### The good folks at Blurb and Balto are making this happen! 

Here's a giant list of TODOs, this time with extra emoji! :tulip: 

A few months out:
- [x] Find a venue and sponsor for the workshop: I think Blurb is interested in hosting this; we can confirm
- [x] Find co-organizers and start going through the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook): 
Once we have a venue/sponsor and organizers, we can:
- [x] Set a date :calendar:  that works for everyone. 
- [x] Set an RSVP limit :two_women_holding_hands::two_women_holding_hands::two_women_holding_hands::two_women_holding_hands: that works for everyone
- [x] Post the workshop to [Bridge Troll](http://www.bridgetroll.org/) :pushpin: 
- [ ] Post the workshop to [Meetup](http://www.meetup.com/sfruby/#calendar) if we don't get enough volunteers from BridgeTroll alone. :traffic_light: 

One to two weeks out, we can:
- [ ] Plan a teacher training :books:, preferably at Blurb or goBalto
- [ ] Order breakfast :coffee: 
- [ ] Order lunch :hamburger: 
- [ ] Find a good place for the afterparty :tropical_drink: 

After the workshop, we can:
- [ ] Party! :tada:
- [ ] Retro :dress: 
- [ ] [Expense](https://atrium.schoolfactory.org/bridgefoundry/node/108690) :moneybag: anything that Blurb or goBalto doesn't cover

**Comment by lilliealbert** [comment]
hey @danigro77, it'd be awesome if you could post a write up about how the workshop went (and the retro notes, if you have them) to the workshop mailing list! Thanks for organizing!!! :tada: :tada: :tada:

**Comment by danigro77** [comment]
Working on it. A visitor from Europa slowed me down ;)
Daniela
