### ISSUE TITLE
RailsBridge Hawaii: Nanakuli Intro to Ruby on Rails Date TBD

### ISSUE THREAD

**Issue by joker2600** [railsbridge/organizing#45]
This workshop's going to be amazing!! Here's what we need to do!

A few months out:
- [ ] Find a venue and sponsor for the workshop. This workshop covers Introduction to Rails.
- [x] Find two co-organizers. It's a lot of work, but always a lot of fun. No experience is necessary; checkout the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook) if it's new to you. (Joseph Heaukulani, Kay Fukuda, Jeffrey Vierra)

Leave a comment below if you're able to host, sponsor or organize! :smile_cat: 

Once we have a a venue, sponsors, and organizers, we can:
- [ ] Work together to set an RSVP limit that works for everyone
- [ ] Post the workshop to [Bridge Troll](http://www.bridgetroll.org/)
- [ ] Post the workshop to [Meetup](http://www.meetup.com/sfruby/#calendar) for publicity 

One to two weeks out, we can:
- [ ] Plan a teacher training
- [ ] Order breakfast
- [ ] Order lunch
- [ ] Find a good place for the afterparty

After the workshop, we can:
- [ ] Party! :tada:   
- [ ] Retro

:tulip:

**Comment by ruchikakumar** [comment]
HI @joker2600 ! Any plans to schedule this? Let us know what we can do to help!

**Comment by lilliealbert** [comment]
hey @joker2600, I'm going to close this issue — feel free to open a new one in the future if you've got a workshop planned!
