### ISSUE TITLE
RailsBridge Hawaii: Web Dev Workshops for the Micronesian Community Date TBD

### ISSUE THREAD

**Issue by joker2600** [railsbridge/organizing#46]
This workshop's going to be amazing!! Here's what we need to do!

A few months out:
- [ ] Find a venue and sponsor for the workshops. These workshops will most likely be consecutive Saturdays. First workshop covers HTML, CSS, and an intro to JavaScript. Second covers Intro to Rails.
- [x] Find two co-organizers. (Joseph Heaukulani, Lino Talley)

Leave a comment below if you're able to host, sponsor or organize! :smile_cat: 

Once we have a a venue, sponsors, and organizers, we can:
- [ ] Work together to set an RSVP limit that works for everyone
- [ ] Post the workshop to [Bridge Troll](http://www.bridgetroll.org/)
- [ ] Post the workshop to [Meetup](http://www.meetup.com/sfruby/#calendar) for publicity 

One to two weeks out, we can:
- [ ] Plan a teacher training
- [ ] Order breakfast
- [ ] Order lunch
- [ ] Find a good place for the afterparty

After the workshop, we can:
- [ ] Party! :tada:   
- [ ] Retro

:tulip:

**Comment by ruchikakumar** [comment]
Same here @joker2600  let me know how we can help/ if this is still happening!

**Comment by lilliealbert** [comment]
hey @joker2600, I'm going to close this issue — feel free to open a new one in the future if you've got a workshop planned!
