### ISSUE TITLE
Early February SF Javascript RailsBridge Workshop for Women at Dev Bootcamp 

### ISSUE THREAD

**Issue by raorao** [railsbridge/organizing#50]
Hey everyone! So @EmFoley and I are interested in hosting a railsbridge early next year. We're still getting the details together, but we're hoping for one of the first weekends in february. And we also want to write some new JS Curriculum!

Any help / advice / suggestions would be appreciated!

**Comment by EmFoley** [comment]
Hi all,

Just fyi, here is the Meetup.com page for this event:
http://www.meetup.com/SF-JavaScript-All-Level-Meetup/events/219558449/

Happy New Year!

Cheers,

Emily

**Comment by lilliealbert** [comment]
Hey @EmFoley & @raorao, have you considered using Bridge Troll for RSVPs? It helps us track student & volunteer attendance workshops and has a lot of tools for communicating / breaking people up into small groups / etc. Here's more about Bridge Troll if you're unfamiliar with it: https://www.bridgetroll.org/about

**Comment by aneyzberg** [comment]
Hey @EmFoley, yes let me know if you need any help setting up the Bridge Troll Page :)

Also @raorao we have had some interest from people in contributing to the javascript curriculum. Would you be open to that? If so let me know :)

**Comment by aneyzberg** [comment]
Hey @EmFoley - let me know if you need any help with the Bridge Troll site :)

Also @raorao - we have had some people interested in contributing to the javascript curriculum. Would you be open to that? Let me know :)

**Comment by EmFoley** [comment]
Hi Anna,

We'd love to use the Bridge Troll site! I'll get working on that right away
and get in touch if I have any questions.

Cheers,

Emily

**Comment by aneyzberg** [comment]
Hey Emily,

That sounds great!

Thank you!
Anna

**Comment by lilliealbert** [comment]
It looks like @raorao's PR to update the JS curriculum levels are in, so the only thing left to do before we publish on Bridge Troll is for the language about who is invited to be updated. 

@EmFoley, can you ping me once that's up to date? 

It would probably make sense to give the people who RSVP'd on Meetup a day's headstart on RSVP-ing before announcing it to the whole RailsBridge SF list, since it'll probably fill up quickly and then the Meetup people would be sad that there wasn't room for them on Bridge Troll.

**Comment by lilliealbert** [comment]
Language that we've used commonly is: 

> This workshop is intended to reach out to women who are interested in learning Ruby on Rails. Men are welcome to come if you find a woman who wants to learn Ruby on Rails and come together. RailsBridge is emphatically queer and trans* friendly.

And it's helpful to include "for Women" in the event title for extra clarity

**Comment by EmFoley** [comment]
Thanks, Lillie- sorry for the delay! Will have those changes up and messages out to the Meetup folks to switch to Bridge Troll today.

Cheers,

Emily

**Comment by EmFoley** [comment]
Hey Lillie,

Quick question- I've updated the language on the Bridge Troll page, but
wanted to also remove the InstallFest- Rao and I decided against it, but I
couldn't find a way to remove a session from the event.

Sorry if I'm missing something obvious! If not, can you let me know how to
do that?

As soon as I can remove the Installfest, I'll message the Meetup.com
respondees, since I want to remove the possibility of additional confusion
over an Installfest.

Thanks so much for your ongoing help with this!

Cheers,

Emily

**Comment by lilliealbert** [comment]
That's actually not something that's currently changeable via the site (it
is before you've saved the event the first time, but not after). I'll jump
into a Rails console and remove that for you tonight. (And will follow up
when it's done!)

On Tue, Jan 20, 2015 at 5:12 PM, Emily Foley <notifications@github.com>
wrote:

> Hey Lillie,
>
> Quick question- I've updated the language on the Bridge Troll page, but
> wanted to also remove the InstallFest- Rao and I decided against it, but I
> couldn't find a way to remove a session from the event.
>
> Sorry if I'm missing something obvious! If not, can you let me know how to
> do that?
>
> As soon as I can remove the Installfest, I'll message the Meetup.com
> respondees, since I want to remove the possibility of additional confusion
> over an Installfest.
>
> Thanks so much for your ongoing help with this!
>
> Cheers,
>
> Emily
>
> On Tue, Jan 20, 2015 at 9:25 AM, Emily Foley <foleyemilym@gmail.com>
> wrote:
>
> > Thanks, Lillie- sorry for the delay! Will have those changes up and
> > messages out to the Meetup folks to switch to Bridge Troll today.
> >
> > Cheers,
> >
> > Emily
> >
> > Sent from my iPhone
> >
> > On Jan 19, 2015, at 1:33 PM, Lillie Chilen <notifications@github.com>
> > wrote:
> >
> > Language that we've used commonly is:
> >
> > This workshop is intended to reach out to women who are interested in
> > learning Ruby on Rails. Men are welcome to come if you find a woman who
> > wants to learn Ruby on Rails and come together. RailsBridge is
> emphatically
> > queer and trans* friendly.
> >
> > And it's helpful to include "for Women" in the event title for extra
> > clarity
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/railsbridge/organizing/issues/50#issuecomment-70564935>
>
> > .
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/railsbridge/organizing/issues/50#issuecomment-70767373>
> .
>



-- 
Lillie Chilen
@lilliealbert
('li-lee shuh-'leen)

**Comment by EmFoley** [comment]
Awesome, thanks so much for filling me in and taking care of that :) I'll
be ready to message everyone when I hear from you!

**Comment by lilliealbert** [comment]
Okay, cool, updated. So now, you do the Meetup thing, and then in a day we announce it to the rest of the world?

**Comment by EmFoley** [comment]
Sounds perfect! Will have that done later tonight after work :)

**Comment by EmFoley** [comment]
All right, email sent to all yes RSVPs on Meetup.com directing them to RSVP
via Bridge Troll!

**Comment by lilliealbert** [comment]
@EmFoley, should I go ahead and publish the event on Bridge Troll? Three days seems like a decent interval to let people RSVP before announcing.

**Comment by EmFoley** [comment]
Sounds good to me, Lillie! Thanks so much!

**Comment by aneyzberg** [comment]
@raorao Hey Rao, The folks at Carbon Five mentioned to me that they want to do a JS curriculum under RailsBridge in Chattanooga. And they were wanting to see the JS curriculum that was developed for the workshop at Dev Bootcamp - but i don't see it up on the RailsBridge site yet. Do you know when we'll get a chance to see the curriculum?

**Comment by lilliealbert** [comment]
Also, looking at the low number of volunteers so far (6 volunteers for 100 students), I'm worried that we're not going to get enough volunteers if we don't get the curriculum in the public ASAP. @raorao, can you share whatever draft version you have?

(It would probably also be a good idea to schedule an evening of teacher training to review the curriculum before the workshop, but the most important thing is getting the curriculum online soon.)

**Comment by raorao** [comment]
totally right. I'll push the current version of the curriculum tonight.

**Comment by lilliealbert** [comment]
Wooooooooo successful workshop!!! 

@EmFoley & @raorao, could you share retro notes / any other reflections with the [workshop mailing list](https://groups.google.com/forum/#!forum/railsbridge-workshops) once you've recovered from organizing?

:smile_cat: :tada: :smile_cat:

**Comment by raorao** [comment]
Will do! I joined the mailing list over the weekend. we'll post something in the next few days.

**Comment by raorao** [comment]
just submitted my notes to the listserv.

One last question: I wanted to send one more thank you email to
volunteers/students, and I was hoping to include a link to the survey
again. Is there anyway to do that? The URLs seem specific to the RSVP.

**Comment by tjgrathwell** [comment]
@raorao I have added in the technology to access the surveys without RSVP ids (https://github.com/railsbridge/bridge_troll/commit/7b5907a06eb8df3b825ea96137ed168170629c21), so you can tell the email people to visit https://www.bridgetroll.org/events/137/surveys/new

**Comment by raorao** [comment]
thanks!
