### ISSUE TITLE
Oakland Apr 3 & 4 Rails Workshop for Women at Pandora

### ISSUE THREAD

**Issue by siruguri** [railsbridge/organizing#55]
Pandora has offered to host and sponsor. More details forthcoming.
@aneyzberg @whatasunnyday.

**Comment by aneyzberg** [comment]
@siruguri Awesome! so happy to hear that!

**Comment by siruguri** [comment]
Adding @sara-gudeman for notifications.

**Comment by whatasunnyday** [comment]
A few months out:
- [x] Find a venue and sponsor for the workshop. This workshop covers HTML, CSS, and an intro to JavaScript. Sponsoring the workshop costs between $400 and $900, depending on the size of the workshop.
Pandora is both the venue and the sponsor.

- [x] Find two co-organizers. It's a lot of work, but always a lot of fun. No experience is necessary; checkout the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook) if it's new to you. (Also, we match up first time organizers with mentors.)
@siruguri and myself are the organizers. We also have a bunch of people who want to help out!

Once we have a a venue, sponsors, and organizers, we can:
- [x] Work together to set an RSVP limit that works for everyone
We're capping at 50.
- [ ] Post the workshop to [Bridge Troll](http://www.bridgetroll.org/)
Waiting on a last email from our contact to confirm the last of the details.
- [ ] Post the workshop to [Meetup](http://www.meetup.com/sfruby/#calendar) for publicity 

One to two weeks out, we can:
- [ ] Plan a teacher training
- [ ] Order breakfast
- [ ] Order lunch
- [ ] Find a good place for the afterparty

After the workshop, we can:
- [ ] Party! :tada:   
- [ ] Retro

**Comment by siruguri** [comment]
Just created the Bridge Troll event - https://www.bridgetroll.org/events/156

**Comment by tjgrathwell** [comment]
I think the dates may not be right

![screen shot 2015-03-16 at 7 21 55 pm](https://cloud.githubusercontent.com/assets/1041691/6680241/95e742ea-cc11-11e4-82d1-42f4bed654cf.png)

**Comment by siruguri** [comment]
Took a few tries, but I think I got it right finally! :) Also removed a
sentence asking for dietary needs to be emailed, per Lillie's observation
via email.

**Comment by whatasunnyday** [comment]
@siruguri Did you also post it on the meet up?

**Comment by siruguri** [comment]
I don't remember doing that the last time, and recently I saw a note on the mailing list discussing whether posting to Meetup causes more confusion than is worth it... @aneyzberg - any thoughts on what's the recommended action re Meetup?

**Comment by siruguri** [comment]
FYI - Pandora has confirmed all logistics, and will be paying for food. Yay! We have a wrap up call on the 27th, let us know if anyone would like to join in on that. We offered to hold some spots for Pandora employees and depending on the number, will raise the RSVP limit to let more waitlisted students in.

**Comment by aneyzberg** [comment]
Yay! That's exciting!

**Comment by lilliealbert** [comment]
Duplicate? It happened!! https://www.bridgetroll.org/events/156
