### ISSUE TITLE
Front End workshop at Carbon Five in SF

### ISSUE THREAD

**Issue by nfiniteset** [railsbridge/organizing#56]
Carbon Five in San Francisco would like to offer up our space for a workshop this year. (More than one workshop even, but let's start here!)
We have a large open space for food and intro talk, many small meeting rooms for classes to break out into, and solid Wi-Fi. We've hosted a number of workshops in the past. 

A few months out:
- [x] Find a venue and sponsor for the workshop. This workshop covers HTML, CSS, and an intro to JavaScript. Sponsoring the workshop costs between $400 and $900, depending on the size of the workshop.
- [x] Find two co-organizers. Courtney from C5 and Sonya from GitHub will organize
- [x] Set the date: March 28, 2015.

Leave a comment below if you're able to sponsor or organize! :smile_cat: 

Once we have a a venue, sponsors, and organizers, we can:
- [x] Work together to set an RSVP limit that works for everyone
- [ ] Post the workshop to [Bridge Troll](http://www.bridgetroll.org/)
- [ ] Post the workshop to [Meetup](http://www.meetup.com/sfruby/#calendar) for publicity 

One to two weeks out, we can:
- [ ] Plan a teacher training
- [ ] Order breakfast
- [ ] Order lunch
- [ ] Find a good place for the afterparty

After the workshop, we can:
- [ ] Party! :tada:   
- [ ] Retro

:tulip: :tulip: :tulip:

**Comment by sundaykofax** [comment]
:hand: for organizing. 

My February is already full, would a date in March be doable? I'm available the 14th, 21, and 28th. (Also preeeetty free in April.)

**Comment by aneyzberg** [comment]
Awesome! @sundaykofax let me know what help if any you might need on the organizing front.

**Comment by courtney** [comment]
I could do the 28th of March but the other weekends I'm out of town.

**Comment by sundaykofax** [comment]
:+1: 28th

**Comment by lohsu** [comment]
Awesome!  But the 28th might not work for me because of a wedding I have to attend..

**Comment by nfiniteset** [comment]
This workshop needs an experienced co-organizer! In anyone with organizing experience willing to help pull this together?

**Comment by sundaykofax** [comment]
@rachelmyers might you be available to help organize this event? What I really mean is "I'm not confident of my experience level, but I'd be glad to do the work and Rachel advises/mentors".

**Comment by aneyzberg** [comment]
Hey @sundaykofax  - Just to let you know - If Rachel Meyers can't organize - I am the new organizing lead for RailsBridge sf - so I would be happy to find you guys another co-organizer. I can also pitch in as needed. Just let me know.

**Comment by sundaykofax** [comment]
>I am the new organizing lead for RailsBridge sf

@aneyzberg that's awesome! Based on my experience last time, it was day-of (really morning-of) that I had trouble navigating. Is it reasonable to think that with a morning-of boost of help, Courtney and I could do the rest (both planning before, where we'll be able to show work via a checkbox) and after the day gets rolling?

**Comment by aneyzberg** [comment]
@sundaykofax -  I think that is totally and completely reasonable. I can plan on also being there as a boost of help that morning - And I can answer any questions you might have along the way :)

**Comment by courtney** [comment]
My biggest concern is how we coordinate the actual teaching. Will people that sign up as volunteers have taught a front end class before?

**Comment by aneyzberg** [comment]
@courtney Generally speaking yes - the volunteers that sign up to teach have taught before. And while it may have happened under some rare circumstances in the past where someone was teaching for the first time - new people usually serve as TA's. The morning of the workshop - the organizer console in Bridgetroll will allow you to auto-arrange classes and select teachers for the classes. I will plan on being there that morning and can help you guys with that - I have a pretty good idea about teachers at this point - and there are usually a couple veteran teachers around who I can also ask to help arrange classes via BrdigeTroll - and they also usually have a good idea about who has taught and who hasn't. Does this help?

**Comment by courtney** [comment]
heck yeah that helps - consider fears allayed!

**Comment by aneyzberg** [comment]
:+1:

**Comment by sundaykofax** [comment]
@courtney do you think 60 students/30 teachers (like last time) are the numbers we want to use? For sponsorship purposes, how much do you think it would cost to cover food? It'd be nice to also cover the teacher drink tickets. I'm going to ask GitHub, so I'd like to figure out a ballpark number.

**Comment by courtney** [comment]
@sundaykofax I think that would be more than enough! that is 2 students per teacher... so I think we could even do 60 students/15 teachers and be totally fine. TAs and myself can help fill in the gaps.

I'll check on ballpark costs for breakfast and lunch. I can also arrange for us to have a dedicated spot at Southside for drinks after... or we can walk down to github to the bar!

**Comment by aneyzberg** [comment]
So just so you both know, as you are thinking about numbers, when you set a numbers for the workshop on Bridgetroll - you can only set the cap for the number of students. The volunteers usually self regulate based on the number of students signed up - but you cannot as of yet specify on Bridgetroll how many teachers vs. ta's you would like. So you just have a general volunteer sign up. In the organizer console you will be able to see who has signed up as a teacher and who has signed up as a TA - but again no way to specifically control for that. So maybe for overall numbers thinking about how many Teachers + TA's you would want to have if you set up a workshop for 60 students.

**Comment by sundaykofax** [comment]
Oh gotcha. Well, I can't imagine having too many TAs and teachers is bad (except when it gets warm in a room, I guess). I'm sure we can adjust the actual food order as needed once we know how many teachers are signing up.

**Comment by aneyzberg** [comment]
Totally, and we can have a general number of people in mind that we want to have total. If needed we can always send volunteers home if there are way too many. We have done this before.

**Comment by sundaykofax** [comment]
I was fantasizing about going out to buy peanut butter and bread like the old days of Girl Scouts.

**Comment by aneyzberg** [comment]
Haha...fair enough.

**Comment by courtney** [comment]
Here are some rough numbers for about 80 folks: 
super casual breakfast (bagel/muffins/coffee), that’s about $300 with a casual lunch (salads, lavash rolls) at about $700-800. Total combined would be around $1000-1100.

**Comment by sundaykofax** [comment]
:octocat: will sponsor the food! They've donated $1000. I have an email with all the details. @courtney I'll forward it to you. 

Next up, setting the RSVP limit and getting this thing onto Bridgetroll and Meetup! @courtney does 60 students sound right, or would you adjust it?

**Comment by courtney** [comment]
60 sounds great - I'm slammed this week so I might be hit or miss on
helping out :(

c

On Mon, Jan 26, 2015 at 10:39 AM, Sonya Green <notifications@github.com>
wrote:

> [image: :octocat:] will sponsor the food! They've donated $1000. I have
> an email with all the details. @courtney <https://github.com/courtney>
> I'll forward it to you.
>
> Next up, setting the RSVP limit and getting this thing onto Bridgetroll
> and Meetup! @courtney <https://github.com/courtney> does 60 students
> sound right, or would you adjust it?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/railsbridge/organizing/issues/56#issuecomment-71512789>
> .
>



-- 
Courtney Hemphill
Carbon Five

415-546-0500 x 20 | http://www.carbonfive.com
<https://twitter.com/chemphill>
<http://www.linkedin.com/in/courtneyhemphill>

**Comment by sundaykofax** [comment]
@courtney that's OK! This is why having multiple organizers is good. WE'RE LIKE THE CLOUD. Spin up another organizer.

@nfiniteset on the next set of tasks (bridgetroll and meetup), any reason to wait? Mind if I set them up?

**Comment by nfiniteset** [comment]
I don't see a reason to wait. Make it real!

**Comment by sonyagreen** [comment]
I'm duplicating details from the [last C5 frontend event](https://www.bridgetroll.org/events/102). I'd like to double check that the times (9:30-5) are what we want, if there are any transportation/parking hints, and decide on the afterparty -- @courtney would you see if we can Southside?

**Comment by courtney** [comment]
I'll check into Southside and there are several parking lots on 2nd street between Howard and Folsom. Street parking is also available and there is usually a lot of it on a Saturday.

**Comment by sundaykofax** [comment]
Our [BridgeTroll event is submitted and pending approval](https://www.bridgetroll.org/events/144). If someone would give it :eyes: to proof it.

**Comment by lilliealbert** [comment]
hey @sundaykofax, just took a look at your event on Bridge Troll, and it looks great! I made a tweak to the name to make it be a little more consistent, and noticed this in the description:

"Read the class level descriptions, then day-of you can join the class you think will best suit your needs." 

We actually ask people to pick their class level as part of the RSVP process, and I just wanted to double check that you knew that. People can definitely update their class level whenever they want (and are encouraged to switch classes during the workshop).

You can preview what the RSVP form looks like for students — this is linked from the organizer console: https://www.bridgetroll.org/events/144/rsvp_preview?role_id=1

**Comment by sundaykofax** [comment]
Whoops! My fault. I did not know that (or, more accurately remember it). I've updated the BridgeTroll event. Thanks for the explanation @lilliealbert.

**Comment by courtney** [comment]
Thanks @sundaykofax!

On Wed, Feb 4, 2015 at 12:06 PM, Sonya Green <notifications@github.com>
wrote:

> Whoops! My fault. I did not know that (or, more accurately remember it).
> I've updated the BridgeTroll event. Thanks for the explanation
> @lilliealbert <https://github.com/lilliealbert>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/railsbridge/organizing/issues/56#issuecomment-72928474>
> .
>



-- 
Courtney Hemphill
Carbon Five

415-546-0500 x 20 | http://www.carbonfive.com
<https://twitter.com/chemphill>
<http://www.linkedin.com/in/courtneyhemphill>

**Comment by lilliealbert** [comment]
@sundaykofax, sure thing!! We have a really great class-division tool that will take the people who have checked in and break them into small groups: https://www.bridgetroll.org/events/144/organize_sections

(You can also run it ahead of time with everybody, but the morning of the workshop, I've found limiting the sorting to people who checked in to be much more helpful.)

If you have any feedback about the app, please do let me know! There are many UX things that we could improve >_<

**Comment by courtney** [comment]
@sundaykofax Question about the afterparty - how many people do you think will go? The bar we were thinking of using has a $500 minimum spend. Is someone sponsoring the drinks? I know in the past we have only paid for teachers and volunteers.

**Comment by sundaykofax** [comment]
>how many people do you think will go?

Good question! I don't have much data on this -- could someone jump in with a ballpark estimate of like, what percentage of students and volunteers go?

>Is someone sponsoring the drinks?

We have $1k to work with from GitHub. If we wanted to give a drink ticket to each of the volunteers, that's like `$6*25volunteers=$150` (I'm estimating lots here). @courtney do you think we can budget ~$850 breakfast and lunch? This seems like the time to mention that I think lighter breakfast fare than last time (bagels and cream cheese) would probably be OK. Coffee/tea for sure, and something hearty (rad granola bars?) to have if you aren't as diligent about [breakfast being the most important thing](https://uproxx.files.wordpress.com/2012/11/bluths-breakfast.gif). I recall in the teacher feedback, someone mentioning having a breakfast a little less carb-y would make for more alert students.

**Comment by aneyzberg** [comment]
@sundaykofax as far as how many people go -  I just asked @rachelmyers , and she said about  50% of students/volunteers attend but she made a good point that we should make sure we have enough space for about 75% .

**Comment by tjgrathwell** [comment]
@sundaykofax @aneyzberg 50% / 75% seems very high to me, but I've been to a lot of workshops where most people didn't make it to the afterparty for whatever reason. 25% seems more realistic to me but I could be pessimistic?

What bar are you thinking of going to that has a "$500 minimum spend"? Are you renting out a section of the bar? My personal stance on afterparty selection is that it shouldn't be anywhere too fancy or expensive, and it's nice for the seating/standing situation to be a little flexible so that attendees can talk to more people than the ones they happened to sit down next to.

**Comment by courtney** [comment]
@aneyzberg thanks for the number check! @tjgrathwell I agree, there is a bar downstairs that offered to open up early for us but then said they wanted to make sure it was worth it. There are plenty of other spots we can go to that I think will have space (it is Saturday afternoon). So I will say no to the bar w/ the minimum.

**Comment by courtney** [comment]
@sundaykofax We could do a Trader Joes run to get some items that are less carby (sliced meats and cheese and yogurt). We can then do fruit and some bagels for the rest. What do you think?

**Comment by sundaykofax** [comment]
@courtney :+1: to a run for what I'm hearing to be a Finnish breakfast :heart_eyes_cat: I could do a Friday (Mar 27) day or evening run.

**Comment by courtney** [comment]
@sundaykofax we've got 33 volunteers and 60 students. I'm going to set up an order for breakfast & lunch from Whole Foods b/c they deliver!! Any objections?

**Comment by sundaykofax** [comment]
None! Are we set on the Southside Spirit House? Is there anything else we need to do beforehand?

I'm remembering back to last time, thinking about what we needed day-of. Nametags and pens – I have a 100-pack of nametags, if needed.

**Comment by courtney** [comment]
I don't think we have nametags, so bring those. We should have everything
else here in the office.

c

On Mon, Mar 23, 2015 at 9:20 AM, Sonya Green <notifications@github.com>
wrote:

> None! Are we set on the Southside Spirit House? Is there anything else we
> need to do beforehand?
>
> I'm remembering back to last time, thinking about what we needed day-of.
> Nametags and pens - I have a 100-pack of nametags, if needed.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/railsbridge/organizing/issues/56#issuecomment-85073253>
> .
>



-- 
Courtney Hemphill
Carbon Five

415-546-0500 x 20 | http://www.carbonfive.com
<https://twitter.com/chemphill>
<http://www.linkedin.com/in/courtneyhemphill>

**Comment by sundaykofax** [comment]
Got it. :name_badge:

**Comment by lilliealbert** [comment]
This totally happened, yay! https://www.bridgetroll.org/events/144
