### ISSUE TITLE
February 20 & 21st Railsbridge workshop Yammer Eng.

### ISSUE THREAD

**Issue by ruchikakumar** [railsbridge/organizing#58]
We are going to try and aim for a monthly railsbridge workshop in 2015! And try for consistency 3rd weekend of the month. I am currently contacting venues for February.

**Comment by aneyzberg** [comment]
@ruchikakumar Orginally engine yard had wanted to do February and we had told them march - so we posted on the old Github issue yesterday to see if they still want February

**Comment by ruchikakumar** [comment]
@aneyzberg i guess my understanding was that is for a front end workshop, so an add on event, not the monthly standard railsbridge  workshop goal? If it is I can close this one out when they confirm.

**Comment by aneyzberg** [comment]
oh..hmmm..I just read through the old issue - and it looks like its a traditional workshop, unless I am misunderstanding. But yes, let's keep this open until they confirm dates in case they want to do march and not February, so we would still need someone :)

**Comment by ruchikakumar** [comment]
@aneyzberg got it, i got them confused with carbon 5! Sorry!

**Comment by elg0nz** [comment]
Hi @ruchikakumar , @aneyzberg  Yammer Engineering was looking to organize one for that week, but since you guys are already have it planned, we would be happy to host it.

**Comment by missherico** [comment]
^^ gonzalo! =D

On Tue, Jan 20, 2015 at 1:47 PM, Gonzalo Maldonado <notifications@github.com

**Comment by ruchikakumar** [comment]
Thanks @elg0nz! We will get back to you shortly if its still open! In the thread above we had a potential sponsor so will verify and get back to you asap! Cheers.

**Comment by elg0nz** [comment]
@missherico we just keep running into each other!

**Comment by ruchikakumar** [comment]
Hi @elg0nz  we would love to have Yammer engineering sponsor for that weekend!  Are you familiar with the process?  First things first if we can confirm the date fri eve/sat day and then how many people you can host up to depending on how much of your space is available to us that weekend.

**Comment by ruchikakumar** [comment]
Hi @elg0nz ! Just checking in if you would still like to host?

**Comment by elg0nz** [comment]
Hi @ruchikakumar sure! Could you send me a PM so I can give you my work email and follow up in there?

**Comment by ruchikakumar** [comment]
Here's a giant list of TODOs, this time with extra emoji! :tulip: 

A few months out:
- [x] Find a venue and sponsor for the workshop: I think EngineYard's :steam_locomotive: interested in hosting this; we can confirm
- [] Find co-organizers and start going through the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook): @shanaclaire, @alenia, and @michelleN from Engine Yard :steam_locomotive: 

Once we have a venue/sponsor and organizers, we can:
- [ ] Set a date :calendar:  that works for everyone. (Late October or Early November looks good) :fallen_leaf: 
- [ ] Set an RSVP limit :two_women_holding_hands::two_women_holding_hands::two_women_holding_hands::two_women_holding_hands: that works for everyone
- [ ] Post the workshop to [Bridge Troll](http://www.bridgetroll.org/) :pushpin: 
- [ ] Post the workshop to [Meetup](http://www.meetup.com/sfruby/#calendar) if we don't get enough volunteers from BridgeTroll alone. :traffic_light: 

One to two weeks out, we can:
- [ ] Plan a teacher training :books:, preferably at Engine Yard :steam_locomotive:, but maybe somewhere else
- [ ] Order breakfast :coffee: 
- [ ] Order lunch :hamburger: 
- [ ] Find a good place for the afterparty :tropical_drink: 

After the workshop, we can:
- [ ] Party! :tada:
- [ ] Retro :dress: 
- [ ] [Expense](https://atrium.schoolfactory.org/bridgefoundry/node/108690) :moneybag: anything that EngineYard :steam_locomotive: doesn't cover

**Comment by celestelayne** [comment]
Hey @elg0nz - is there a place near Yammer's office that you would recommend for a post-workshop happy hour? thanks.

**Comment by elg0nz** [comment]
Hi Celeste,
The Hot Spot has recently been remodelled and it's both nice and and fun.
http://www.yelp.com/biz/the-hot-spot-san-francisco

Beer Hall is also a good option, but it only has room for like 15 people
and gets crowded on Fridays so it might not be ideal for it but we can try.

Best,
Gonzalo

**Comment by celestelayne** [comment]
Thanks @elg0nz - I'll contact The Hot Spot (seems the better choice) for Saturday -- Celeste

**Comment by lilliealbert** [comment]
This was a great workshop!! :tada: :tada: :tada:
