### ISSUE TITLE
RailsBridge write/plan/code night 

### ISSUE THREAD

**Issue by ruchikakumar** [railsbridge/organizing#59]
We are going to try and aim for a regular RailsBridge write/plan/code night monthly or every other month.  Would ideally like to get one in before Feb end. Lets start sourcing for venues. @aneyzberg @celestelayne would Galvanize or Maker square be a possible fit?

**Comment by aneyzberg** [comment]
@ruchikakumar Celeste and I were actually just talking about this yesterday. I think one of those venues could work

**Comment by celestelayne** [comment]
@aneyzberg @ruchikakumar MakerSquare is holding the first week in March for us. We just need to give them a day/date.

Celeste

**Comment by ruchikakumar** [comment]
Same page :-)

**Comment by ruchikakumar** [comment]
cool, do we need to aim for before that too? Or is that close enough? I think Monday or Tuesday could be a good idea...

**Comment by aneyzberg** [comment]
Maybe we could do one in Feb at Galvanize? And one at MakerSquare in March?

**Comment by celestelayne** [comment]
@aneyzberg @ruchikakumar I'll reach out to Bru at Galvanize and see if I can get a date on their calendar for FebFebruary

**Comment by celestelayne** [comment]
So, I'll email Rachel at MakerSquare and have her hold the Tuesday date for us. Does that work for yu guys?

**Comment by aneyzberg** [comment]
works for me :+1:

**Comment by siruguri** [comment]
Would love to volunteer and also learn about holding similar events in East Bay... do I understand that the date is still undecided? The last message from @celestelayne suggested a specific Tuesday...

**Comment by lilliealbert** [comment]
hey all, it turns out Omada can host in February, if you haven't already secured a venue!

**Comment by aneyzberg** [comment]
that sounds good to me! @ruchikakumar @celestelayne would that work?

**Comment by celestelayne** [comment]
@ruchikakumar @aneyzberg that works for me. @lilliealbert what day/date works best for Omada? i think we were pushing for the first week in Feb to offset the third week for RB ... but it's the first one so we can always be flexible

**Comment by aneyzberg** [comment]
I think @lilliealbert mentioned february 10th or 11th? is that right? would that work?

**Comment by celestelayne** [comment]
Yes, Tuesday 10th is best for me.

**Comment by lilliealbert** [comment]
The Omada operations team got back to me, and Wednesday, Feb 11th would be better for them. I told them we'd plan on starting at 6:30pm and have about 25 people (which I made up!!).

**Comment by celestelayne** [comment]
ok

**Comment by aneyzberg** [comment]
That sounds Great! @lilliealbert  - this is something we would be posting on Bridgetroll right?

**Comment by lilliealbert** [comment]
Yeah, totally. How does this event look? https://www.bridgetroll.org/events/139

**Comment by celestelayne** [comment]
this looks great.

**Comment by aneyzberg** [comment]
Looks great to me!

**Comment by lilliealbert** [comment]
ALSO I added you all as chapter leads, so now you should be able to edit
any SF event, as well as see the private contact info / notes fields for
all the SF locations!

On Thu, Jan 22, 2015 at 12:29 PM, Anna Neyzberg <notifications@github.com>
wrote:

> Looks great to me!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/railsbridge/organizing/issues/59#issuecomment-71092703>
> .
>



-- 
Lillie Chilen
@lilliealbert
('li-lee shuh-'leen)

**Comment by aneyzberg** [comment]
@lilliealbert is there anything else that I need to help you with for this event, other than possibly setup for day of?

**Comment by lilliealbert** [comment]
This happened! https://www.bridgetroll.org/events/139
