### ISSUE TITLE
Rails Bridge Yilan, Taiwan on 3/21/2015

### ISSUE THREAD

**Issue by jane-shih** [railsbridge/organizing#60]
Hi all,
We are hosting Rails Bridge Yilan on 3/21.
There are a few questions I would need help with:
1) Is there a standard process to create a webpage for registration info so we could publish on the homepage of rails bridge? We have a volunteer-ChiunHau to help create the webpage.
2) Is there possibility to get sponsorship from Rails Bridge community in terms of $?
3) We currently have a few sponsors in line to help with banners, stickers, venue. Our coaches are organized by sdlong(very appreciated). This is a small scale workshop (30 students, 10 coaches).

Thanks,
Jane

**Comment by lilliealbert** [comment]
1. You can use Bridge Troll to publish your event and manage RSVPs by logging in and clicking the  "Organize Event" button: http://www.bridgetroll.org/. This will create a page on Bridge Troll that will also show up on the RailsBridge.org home page, and this is where students and volunteers will RSVP to the workshop.

2. It is definitely possible to get financial support from RailsBridge for your workshop. If you have sponsors who can cover the food or donate a venue, that's awesome, but if not we can figure something out. You can email board@railsbridge.org to start that process.

Here's our guide for planning your first, small workshop: https://github.com/railsbridge/docs/wiki/Minimum-Viable-Workshop

**Comment by jane-shih** [comment]
Appreciate the quick response.
I've created an event on bridge troll and will contact board@railsbridge.org
soon.
https://www.bridgetroll.org/events/147

Please let me know if I miss anything.
Thanks,
Jane

On Mon, Feb 9, 2015 at 1:40 PM, Lillie Chilen <notifications@github.com>
wrote:

>
>    1.
>
>    You can use Bridge Troll to publish your event and manage RSVPs by
>    logging in and clicking the "Organize Event" button:
>    http://www.bridgetroll.org/. This will create a page on Bridge Troll
>    that will also show up on the RailsBridge.org home page, and this is where
>    students and volunteers will RSVP to the workshop.
>    2.
>
>    It is definitely possible to get financial support from RailsBridge
>    for your workshop. If you have sponsors who can cover the food or donate a
>    venue, that's awesome, but if not we can figure something out. You can
>    email board@railsbridge.org to start that process.
>
> Here's our guide for planning your first, small workshop:
> https://github.com/railsbridge/docs/wiki/Minimum-Viable-Workshop
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/railsbridge/organizing/issues/60#issuecomment-73460011>
> .
>



-- 
Jane Shih
Co-Founder and CEO
Cell:+886-979-487-077
*WeTogether.co <http://www.WeTogether.co>*

**Comment by jane-shih** [comment]
when will the event be published? please let me know if i should edit anything else to get approval.
thanks,
Jane

**Comment by lilliealbert** [comment]
Hi Jane!

Thinking about this more, I'm realizing that maybe Bridge Troll isn't the best tool, since all of the survey questions are in English and we haven't internationalized anything within it. It might be better for the people signing up if you use a different event management tool that supports Mandarin. Things like the [class levels](https://www.bridgetroll.org/events/147/levels) on the RSVP form could be tough for someone with limited English skills to understand.

But, if you think that it's not a problem, I can definitely go ahead and approve your event on Bridge Troll. Let me know what you think.

**Comment by jane-shih** [comment]
Thanks Lillie.
Based on your feedback, I've added a few notes and chinese explanation on
the event page.
We'll also provide detailed instruction for students to follow when they
register on our marketing announcement.
We'd like the event to be published as normal process.
Thanks much,
Jane

On Wed, Feb 11, 2015 at 4:10 AM, Lillie Chilen <notifications@github.com>
wrote:

> Hi Jane!
>
> Thinking about this more, I'm realizing that maybe Bridge Troll isn't the
> best tool, since all of the survey questions are in English and we haven't
> internationalized anything within it. It might be better for the people
> signing up if you use a different event management tool that supports
> Mandarin. Things like the class levels
> <https://www.bridgetroll.org/events/147/levels> on the RSVP form could be
> tough for someone with limited English skills to understand.
>
> But, if you think that it's not a problem, I can definitely go ahead and
> approve your event on Bridge Troll. Let me know what you think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/railsbridge/organizing/issues/60#issuecomment-73774142>
> .
>



-- 
Jane Shih
Co-Founder and CEO
Cell:+886-979-487-077
*WeTogether.co <http://www.WeTogether.co>*

**Comment by lilliealbert** [comment]
@jane-shih Sounds good! 

Can you confirm for me that there's language in the announcement that explains that the event is targeting an population that is underrepresented in tech, and could you update the title of the event to reflect what group of people (women, I'm guessing from your email to the board) it's for? Something like "RailsBridge Yilan Ruby on Rails Workshop for Women" is the pattern we've often used.

**Comment by jane-shih** [comment]
Yes, I've also changed the title of the workshop. 
Thanks,
Jane

**Comment by lilliealbert** [comment]
Awesome, thank you! Published.

**Comment by jane-shih** [comment]
Thanks much Lillie.
We are on track to market the event and the organizers are all very excited
to see our event on the front page of railsbridge.org.
Do you know when we'll get our sponsorship notice?
If RailsBridge would like to treat my company as one of the partner
organizations outside of US, I am open to discuss and develop a program to
cohost open workshops in Taiwan.
Thanks,
Jane



On Thu, Feb 12, 2015 at 1:40 AM, Lillie Chilen <notifications@github.com>
wrote:

> Awesome, thank you! Published.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/railsbridge/organizing/issues/60#issuecomment-73926350>
> .
>



-- 
Jane Shih
Co-Founder and CEO
Cell:+886-979-487-077
*WeTogether.co <http://www.WeTogether.co>*

**Comment by lilliealbert** [comment]
Hi Jane! How did the workshop go?

**Comment by jane-shih** [comment]
It went well. Check out the pics here.
https://m.facebook.com/story.php?story_fbid=824610687621406&id=763277990421343

 :)

Our 4/25 FE workshop is also on schedule. Over 30 people rsvped. If using
bridge troll is required to register, please let me know.
http://www.meetup.com/Taipei-Women-in-Technology/events/220447866/

Thanks,
Jane


Sent from my iPhone

On Apr 14, 2015, at 9:10 AM, Lillie Chilen <notifications@github.com> wrote:

Hi Jane! How did the workshop go?

—
Reply to this email directly or view it on GitHub
<https://github.com/railsbridge/organizing/issues/60#issuecomment-92550394>.

**Comment by lilliealbert** [comment]
Glad this went well! Thanks for the pics!

**Comment by jane-shih** [comment]
Hi Lillie,
I have not gotten the sponsorship. Could you direct me to the right person to get the fund transferred please?

Thanks much,
Jane

**Comment by lilliealbert** [comment]
@jane-shih Could you send a follow up email to finance@railsbridge.org? We've got a new finance committee these days, so you'll want to work with them on it.
