### ISSUE TITLE
SF March 20 - 21 RailsBridge Workshop for Women at Bloc.io

### ISSUE THREAD

**Issue by aneyzberg** [railsbridge/organizing#61]
Here's a giant list of TODOs, this time with extra emoji! :tulip: 

A few months out:
- [x] Find a venue and sponsor for the workshop: Bloc.io
- [x] Find co-organizers and start going through the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook): from Yammer :steam_locomotive: 
- [ ] Find co-organizers from Railsbridge Volunteers and start going through the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook)

Once we have a venue/sponsor and organizers, we can:
- [x] Set a date :calendar:  that works for everyone. :fallen_leaf: 
- [x] Set an RSVP limit :two_women_holding_hands::two_women_holding_hands::two_women_holding_hands::two_women_holding_hands: that works for everyone
- [ ] Post the workshop to [Bridge Troll](http://www.bridgetroll.org/) :pushpin: 
- [ ] Post the workshop to [Meetup](http://www.meetup.com/sfruby/#calendar) if we don't get enough volunteers from BridgeTroll alone. :traffic_light: 

One to two weeks out, we can:
- [ ] Plan a teacher training :books:, preferably at Bloc.io :steam_locomotive:, but maybe somewhere else
- [ ] Order breakfast :coffee: 
- [ ] Order lunch :hamburger: 
- [ ] Find a good place for the afterparty :tropical_drink: 

After the workshop, we can:
- [ ] Party! :tada:
- [ ] Retro :dress: 
- [ ] [Expense](https://atrium.schoolfactory.org/bridgefoundry/node/108690) :moneybag: anything that Bloc.io :steam_locomotive: doesn't cover

**Comment by miss-danie-d** [comment]
Ready to get my organizing on!

**Comment by lilliealbert** [comment]
This happened!! :tada: :tada: https://www.bridgetroll.org/events/154
