### ISSUE TITLE
RailsBridge workshop Colima, México March 20 - 21

### ISSUE THREAD

**Issue by sixviv** [railsbridge/organizing#63]
Here's a giant list of TODOs, this time with extra emoji! :tulip:

A few months out:
- [x] Find a venue and sponsor for the workshop: One Login
- [ ] Find co-organizers and start going through the workshop cookbook
- [ ] Find co-organizers from Railsbridge Volunteers and start going through the workshop cookbook

Once we have a venue/sponsor and organizers, we can:
- [x] Set a date :calendar: that works for everyone. :fallen_leaf:
- [ ] Set an RSVP limit :two_women_holding_hands::two_women_holding_hands::two_women_holding_hands::two_women_holding_hands: that works for everyone
- [ ] Post the workshop to Bridge Troll :pushpin:
- [ ] Post the workshop to Meetup if we don't get enough volunteers from BridgeTroll alone. :traffic_light:

One to two weeks out, we can:
- [ ] Plan a teacher training :books:
- [ ] Order breakfast :coffee:
- [ ] Order lunch :hamburger:
- [ ] Find a good place for the afterparty :tropical_drink:

After the workshop, we can:
- [ ] Party! :tada:
- [ ] Retro :dress:
- [ ] Expense :moneybag: anything that Bloc.io :steam_locomotive: doesn't cover

**Comment by lilliealbert** [comment]
I'm not sure if this workshop ended up happening — I can't find it on Bridge Troll or online anywhere! If this was on Meetup or Eventbrite, could you send me a link, @sixviv, so I can but it in the list of workshops that have happened?

**Comment by sixviv** [comment]
@lilliealbert sorry I never updated this but we had it. Here's the event: http://www.meetup.com/codificadas/events/220739171/
