### ISSUE TITLE
June 19 & 20 SF RailsBridge workshop @ Stitch Fix

### ISSUE THREAD

**Issue by gkop** [railsbridge/organizing#67]
A few months out:

- [x] Find a venue and sponsor for the workshop: Stitch Fix
- [x] Find co-organizers and start going through the workshop cookbook: from Stitch Fix
- [x] Find co-organizers from Railsbridge Volunteers and start going through the workshop cookbook: co-organizers are Gabe and Neeharika

Once we have a venue/sponsor and organizers, we can:

- [x] Set a date  that works for everyone. 
- [x] Set an RSVP limit  that works for everyone
- [x] Post the workshop to Bridge Troll 
- [x] Post the workshop to Meetup if we don't get enough volunteers from BridgeTroll alone. 

One to two weeks out, we can:

- [x] Plan a teacher training, preferably at Stitch Fix , but maybe somewhere else
- [x] Order babysitter
- [x] Order breakfast 
- [ ] Order lunch 
- [x] Find a good place for the afterparty 

After the workshop, we can:

- [x] Party! 
- [x] Retro 
- [x] Expense  anything that Stitch Fix doesn't cover

**Comment by aneyzberg** [comment]
Thanks for a great workshop everyone!
