### ISSUE TITLE
Palo Alto, July 18, HTML, CSS, JavaScript workshop at Groupon

### ISSUE THREAD

**Issue by livash** [railsbridge/organizing#71]
Organizer: Olena Ivashyna (@livash)
Venue: Groupon, 3101 Park Blvd, Palo Alto
Date: July 18, 2015
Curriculum: HTML, CSS, JavaScript
Size: 50-60 people total

Event will be fully sponsored by Groupon:
- [ ] Get a mentor from RailsBridge
- [ ] Post the workshop to [Bridge Troll](http://www.bridgetroll.org/)
- [ ] Post the workshop to [Meetup](http://www.meetup.com/sfruby/#calendar) for publicity 
- [ ] Order breakfast
- [ ] Order lunch (Chipotle)
- [ ] Order food and drinks for after party.

After the workshop, we can:
- [ ] Retro
- [ ] After party will be held in a Game Room at Groupon office.

**Comment by beverlynelson** [comment]
@livash this is so exciting.   Sent an email and cc'd @lilliealbert.  Not to worry, we'll get you connected with a mentor.

**Comment by aneyzberg** [comment]
@livash please let me know what questions you may have. I can definitely help find a mentor as well :)

**Comment by lilliealbert** [comment]
@btelles & @ravasthi are two people who have made workshops happen on the peninsula in the past, so they would be great people to talk to.

**Comment by ravasthi** [comment]
@livash I'm happy to help however I can. Shall we set up a time to chat?

**Comment by livash** [comment]
Thank you guys for responding and being supportive.

Richa or Anna,
could you help me with setting up a page on BridgeTroll announcing the
event?  The announcement will be very much similar to
https://www.bridgetroll.org/events/131 . Somehow I can not find an option
to post an event.

Richa, I would love to take you on an offer to setup time to chat. How
about Thursday evening, July 2 (anytime after 5pm).  I can give you a call
or you can call me at 650-223-4453.

Thanks,
Olena

**Comment by aneyzberg** [comment]
@livash this url should help - https://www.bridgetroll.org/events/new - let me know if you have any questions :)

**Comment by ravasthi** [comment]
Hi Olena, 

How about Thursday at 8pm PDT?

Couple of quick notes based on my past experience: I've typically had a harder time finding volunteers―especially teaching volunteers―for the peninsula RailsBridge workshops than I've seen happen in SF, so if you don't already have a bunch of volunteers lined up, I'd strongly recommend limiting signups until you have volunteers enough to cover students. I personally like to have one teaching volunteer (teacher or TA) per 5 students, to make sure everyone gets the attention they need, but you can realistically expect one volunteer to handle up to 10 students with reasonable comfort. 

--
Richa

**Comment by livash** [comment]
Anna,
thanks for the link :)

Richa,
How about Thursday at 8pm PDT sounds good.

About volunteers. I have already a list of Groupon Engineers who would like
to volunteer as TAs. So I think I should be fine there. Groupon has an
employee volunteer program, and in general people are eager to volunteer.

We can chat about it during the call.

Thanks,
Olena

**Comment by ravasthi** [comment]
Great, talk to you later tonight! I'll call your number. 

--
Richa

**Comment by livash** [comment]
RailsBridge Front End workshop for Women at Groupon is happening :)

Check out the official posting and let me know if anything looks a miss.

https://www.bridgetroll.org/events/171

And I would super appreciate if someone from RailsBridge could attend.

Thanks,
Olena

**Comment by livash** [comment]
Hi guys,
can someone please approve my workshop such that students and volunteers
can sign up?

https://www.bridgetroll.org/events/171

or let me know what I need to do to get it approved.

Thanks,
Olena

**Comment by lilliealbert** [comment]
This workshop totally happened! :tada: :tada: :tada:

@livash, if you have notes from the retro, we'd love to get them on the organizing mailing list!

Thanks for putting on this workshop! :heart:
