### ISSUE TITLE
mini intermediate workshop: open source pairing, at Carbon Five 7/14 evening

### ISSUE THREAD

**Issue by ultrasaurus** [railsbridge/organizing#72]
I had an idea for an intermediate workshop where we would pair more experienced devs (anyone who knows JS and/or Ruby who has done a pull request before and is comfortable diving into a new open source project) with workshop grads.

I have a new [open source project](https://github.com/18F/open-data-maker) I want to highlight  -- it is a good-for-the-world open data project that will feature an exciting new data set and could end up getting some news coverage in late summer (was originally going to include Bridge Troll too, but since Carbon Five is already focusing their July "junior jump" series on that, I want to try this out with an evening event focus on just one project)

I'm proposing that we do promotion/signups via Bridge Troll, and only let in as many students as we have volunteers for them to pair with.

- [x] need confirmation from Jeremy Molony on date/location
- [x] confirmation that this is appropriate use of Bridge Troll @lilliealbert 
- [x] 4-6 volunteers to seed the event with -- please chime in on this issue if you are interested in being the more experienced side of a pair (we'll have a range of issues to work on so you don't need to be super experienced)

**Comment by Holyoke** [comment]
I would actually love that. I've been involved with workshop and recent
graduates as volunteers for RailsBridge events before. There are quite a
few RailsBridge grads who made the jump into bootcamps or CS schooling, so
it'd be cool to still be active with their web dev journey.

An open source project would be great for portfolio and experience in
general because RailsBridge has a great community of engineers.

- Jason

**Comment by lilliealbert** [comment]
@ultrasaurus Seems a legit use of Bridge Troll! You can start with as many student spots as you have volunteers, and then rachet up the number as more volunteers sign up :D

**Comment by siruguri** [comment]
+1 - I had a similar proposal brewing, so I'm glad someone brought this up. There's a space in the East Bay that's willing to donate their building for evening events, and I was going to propose doing multiple InstallFests. What do folks think of that as a "mini" alternative, to help beginners make progress without the commitment of a full weekend workshop?

**Comment by aneyzberg** [comment]
I would be interested in helping with this.

**Comment by shamus** [comment]
@ultrasaurus I was out of the office yesterday, I should know about the space today!

**Comment by shamus** [comment]
Also, if it wasn't clear I'm down to pair that night :smiley:

**Comment by siruguri** [comment]
I would sign up too ... though it's so far out, I might have to just bookmark it for now.

(And @aneyzberg - thanks!)

**Comment by ultrasaurus** [comment]
sorry for the typo -- we're hoping to do this soon!

**Comment by shamus** [comment]
@ultrasaurus C5 is psyched to host

**Comment by siruguri** [comment]
Oh ... I'm busy Tue nights in July ... next time!

**Comment by ultrasaurus** [comment]
@shawnbot will be able to join us and volunteer to pair on JS

**Comment by ultrasaurus** [comment]
event is posted:  https://www.bridgetroll.org/events/174
please sign up as a volunteer if you are up for pairing -- there are already students on the waitlist!

**Comment by ultrasaurus** [comment]
closing this issue, the event went really well from my perspective and everyone I talked to said they would like to do it again.

My notes:  we should accept more students than volunteers, we had a bunch of 'no shows' which was too bad since there was a waitlist.  We had at least one group of three which seemed to go well.
