### ISSUE TITLE
July 18th SF RailsBridge at DevBootcamp

### ISSUE THREAD

**Issue by miss-danie-d** [railsbridge/organizing#73]
Organizer: TBD 
Venue: Dev Bootcamp 
Date: July 17th & 18th 
Curriculum: JavaScript

Here's what we still need to do
- [ ] Find two co-organizers. It's a lot of work, but always a lot of fun. No experience is necessary; checkout the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook) if it's new to you. (Also, we match up first time organizers with mentors.)
- [ ] Work together to set an RSVP limit that works for everyone
- [ ] Post the workshop to [Bridge Troll](http://www.bridgetroll.org/)

Beginning July 6th:
- [ ] Plan a teacher training
- [ ] Order breakfast
- [ ] Order lunch
- [ ] Find a good place for the afterparty

After the workshop, we can:
- [ ] Party!
- [ ] Retro

**Comment by lilliealbert** [comment]
This seems to have happened!! :tada: :tada: :tada:

@miss-danie-d, could you or Christina share the retro notes?
