### ISSUE TITLE
Cleveland, OH Workshop, September 2015 (@pzula)

### ISSUE THREAD

**Issue by pzula** [railsbridge/organizing#75]
This workshop's going to be amazing!! Here's what we need to do!

A few months out:
- [x] Decide on a date!! (September 11th and 12th)
- [x] Find a venue (see <http://railsbridge.org/help/host>) (LeanDog)
- [x] Find sponsors for the workshop. This workshop covers Rails. Sponsoring the workshop costs between $800 - $1,000, depending on the size of the workshop. 
- [ ] Find two co-organizers. It's a lot of work, but always a lot of fun. No experience is necessary; checkout the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook) if it's new to you. 

Leave a comment below if you're able to host, sponsor or organize! :smile_cat: 

Once we have a a venue, sponsors, and organizers, we can:
- [x] Work together to set an RSVP limit that works for everyone (set it to 35 based on last year)
- [x] Get people to volunteer to teach workshop sessions (need about 8-10)
- [ ] Find a few people to offer baby-sitting in one of the rooms at the venue
- [x] Update the website (http://clevelandrailsbridge.org/)
- [x] Make posters to hang up in prominent places at local colleges/universities
- [x] Contact digital arts and comp sci departments of local colleges/universities to forward announcement email
- [x] Post the workshop to [Bridge Troll](http://www.bridgetroll.org/)
- [ ] Post the workshop to [Meetup](http://www.meetup.com/sfruby/#calendar) for publicity 
- [ ] Coordinate with Detroit for a virtual workshop hangout! (Same weeekend) @jdantonio 

One to two weeks out, we can:
- [x] Plan a teacher training
- [ ] Order breakfast
- [ ] Order lunch
- [ ] Find a good place for the afterparty
- [ ] Conduct the teacher training

After the workshop, we can:
- [ ] Party! :tada:   
- [ ] Retro

:tulip:

**Comment by pzula** [comment]
**Dates to consider:** 
- [ ] September 4th & 5th
- [x] September 11th & 12th

**Comment by ascendantlogic** [comment]
1. I'm fine with either September date.
1. I assume LeanDog would be ok to host? I could see if a few friends in Independence know of places down there if for some reason LeanDog doesn't work out.
1. I have a re-affirmed commitment of sponsorship dollars from the CEO of DecisionDesk to the tune of 2-400 dollars, depending on the final costs.
1. I just joined the board of a local charity so I'm not sure I'll have time to be a co-organizer. But if no one else is able to fill that role I can see if I can manage it.

I see the line item for teacher training but not one for actually lining up teachers. Are the co-organizers also supposed to be the people leading the event from a learning perspective?

**Comment by pzula** [comment]
Thanks @ascendantlogic! 

2. Lets work with @joelbyler to see if LeanDog would be OK for those potential dates
3. Let also work with @joelbyler and see if we can get the sponsorship check made out to CLE Ruby Brigade. This would work best if CLE Ruby Brigade also had a debit card that could be used to make the payments for the food providers / domain name
4. It's fine if you can't co-organize! You could still teach, though!

And for the teacher training, good point, my checklist did not include finding teachers to volunteer! I added that line item, as well as actually conducting the teacher training. We need about 8-10 teaching volunteers.

**Comment by joelbyler** [comment]
@pzula, @ascendantlogic,

Sorry it took so long to get back to you, I've been out of town on a vacation without an internet connection.  I've already talked to the folks at LeanDog and we would love to host this on the boat again.  I'll run the dates by the folks in the office tomorrow to confirm.  For me 9/4 & 9/5 are the best days, though it is a holiday weekend so I'm not sure how that will affect participation.

I'll see what I can do to setup a "Christmas Savings Account" for this event under the Cleveland Ruby Brigade bank account.  That should be fine, and @pzula I can set you up with a card if you need one.  Let me know.

**Comment by ascendantlogic** [comment]
So @katieincleveland is suuuuuper excited about this and has offered to help in any way she can to help get it off the ground. She is definitely going to want to attend as a student so she'll not want to be tied up during the event but has offered assistance organizing and getting it going.

**Comment by katieincleveland** [comment]
hi @pzula! and thanks @ascendantlogic!

I am really looking forward to this and would love to help in any way that I can, please let me know if there is anything I can do! I am so grateful for your time and dedication to organizing this.

**Comment by joelbyler** [comment]
@kmckee and @glamouracademy are also interested in helping to TA.

**Comment by joelbyler** [comment]
@pzula, I just realized that the Cleveland Airshow is scheduled for Sept 5, 6, 7 which will make the LeanDog boat a very busy place for the weekend.  I think we're going to have to rule that weekend out.  I can make Sept 12th (Saturday) but will need someone to fill in for me on Friday night.

**Comment by jdantonio** [comment]
One of my Test Double coworkers is doing RailsBridge in Detroit Sept. 11-12. We could consider joining forces and doing a join, virtual event. That might be kind of cool. https://twitter.com/crebma/status/622426597547601921

**Comment by pzula** [comment]
Awesome, thanks @joelbyler and @jdantonio! Let's go for September 11th and 12th! Is Leandog OK with that date?

**Comment by pzula** [comment]
I've updated the website (http://clevelandrailsbridge.org), and posted the workshop to BridgeTroll at https://www.bridgetroll.org/events/178. Volunteers/TA's can sign up at that link (cc: @kmckee and @glamouracademy).   @katieincleveland, I'd love your help with spreading the word! We need some outreach to let people in the area know about the event!

**Comment by pzula** [comment]
@joelbyler Let's go ahead and get that account set up for the event! We'll need a card to charge food items to :)

**Comment by pzula** [comment]
@glamouracademy and @katieincleveland, is there a better way to contact you outside of this github issue?

**Comment by katieincleveland** [comment]
@pzula the best way to reach me is via email, katieincleveland@gmail.com :)

**Comment by glamouracademy** [comment]
@pzula charlottechang.ny_at_gmail

**Comment by jdantonio** [comment]
Welcome @glamouracademy! It'll be great to work with you again!

**Comment by pzula** [comment]
@jdantonio Ping on "Coordinate with Detroit for a virtual workshop hangout!" item above -- any progress on this?

**Comment by pzula** [comment]
this was a great event! Looking forward to 2016!
