### ISSUE TITLE
Open Source Pairing workshop: 8/19 @ Carbon 5

### ISSUE THREAD

**Issue by JasonEb** [railsbridge/organizing#79]
Open Source Pairing Workshop continues!

background: an intermediate workshop where more experienced devs (anyone who knows JS and/or Ruby who has done a pull request before and is comfortable diving into a new open source project) are paired with workshop grads.

Project: [open source project](https://github.com/18F/open-data-maker) -- it is a good-for-the-world open data project that will feature an exciting new data set, utilizing Ruby and JavaScript. 
- [x] location and date: Carbon Five, 8/19/2015
- [x] organizers: @holyoke, @shamus , @aneyzberg 
- [x] create Bridge Troll event after confirmation with organizers and venue
- [x] seed volunteers 

Look like we'll be hosting 10 volunteers and 16 students for Wednesday 8/19 at Carbon Five.

**Comment by shamus** [comment]
Carbon Five is confirmed for 8/19

**Comment by JasonEb** [comment]
How many volunteers and students should we anticipate? Given the traction of the workshop, I feel like setting it at 10 volunteers and 10 students is safe.

**Comment by shamus** [comment]
Hi everybody, what is the status on this workshop? Is there a bridgetroll event? Are the 18f folks confirmed for this evening?

**Comment by JasonEb** [comment]
@shamus I was waiting on confirmation how many attendees to set for the BridgeTroll event at Carbon Five. I'm guessing 20 expected guests is okay for Carbon Five? I can go ahead and create the BridgeTroll in order to confirm planning, then I'll confirm if @ultrasaurus and @shawnbot are going.

**Comment by shamus** [comment]
I see. Yes, we can accommodate twenty

**Comment by ultrasaurus** [comment]
@Holyoke @aneyzberg @shamus Shawn is out of town this week.  It would be great if we could do a little brainstorming in advance about how to structure the Javascript work.  Would anyone be available Tues lunch or Tues evening to do some advance work on this?  I think getting some JS dependencies into the Jekyll app could really help -- maybe integrating PR from @slhaines  and creating a layout and separate CSS file?  also just brainstorming what people could do with the API that would be useful as samples.

Also, can someone send an email about making sure everyone has the app set up?  Here's an edited version of the email I sent before the first workshop:

```
First -- thank you for joining us in this new open source workshop!

IMPORTANT: There's a waitlist for this event, so if you are a student and are not coming, please update your RSVP to give up your spot to someone else.  This goes double for volunteers, since I'm carefully keeping a good ratio of volunteers to students.

Everyone should download the code and set up your installation before Wed:
https://github.com/18F/open-data-maker

check out the INSTALL instructions https://github.com/18F/open-data-maker/blob/dev/INSTALL.md) -- there's an easy bootstrap script that if you are on a Mac with homebrew, but the elasticsearch download  can take a while.

With your help we'll be working on adding some presentation and interactive elements and adding features to the API.  We'll likely continue to use Census data on Tues, but Sarah will be able to share with you how we will to use this software to empower future students of America with new Open Data later this fall.

We have set up a Google Group https://groups.google.com/forum/#!forum/open-data-maker, so it will be easy for people to ask questions and get an answer quickly from any volunteer who has already set up their environment.  Of course, feel free to contact me directly too.

I'm very excited about seeing you all on Wed!
```

**Comment by shamus** [comment]
I'd be happy to brainstorm over lunch on Tuesday @ultrasaurus.  We should definitely talk layout, its not a straight forward path with liquid, as @slhaines and I found out last event when we tried to do that work.

**Comment by JasonEb** [comment]
@ultrasaurus Unless noted otherwise, I'll  send an email tonight to all the students and volunteers with that email about setting up their environment.

**Comment by aneyzberg** [comment]
@ultrasaurus Unfortunately I cannot meet tomorrow at lunch, but could tomorrow evening. Let me know if you decide to meet then. Since Jason is sending out the email, let me know what else I can help with.

**Comment by ultrasaurus** [comment]
Ack!  Today has filled up with things and need to be home in the late afternoon / early evening.  Anyone up for a hangout around 8p?  @aneyzberg @shamus @Holyoke or anyone else who wants to scrub in?

**Comment by aneyzberg** [comment]
@ultrasaurus I can do a hangout around 8pm

**Comment by JasonEb** [comment]
I'm going to be coming back from Mountain View tonight so I won't be able to hangout too much, but if the video link is provided I can drop by and at least provide moral support.

**Comment by ultrasaurus** [comment]
here's a hangout link:  https://plus.google.com/hangouts/_/ultrasaurus.com/open-source?authuser=0

**Comment by ultrasaurus** [comment]
@Holyoke @aneyzberg we've just got 1 volunteer on the waitlist -- I think we should let more volunteers in, if we've got 'em... how 'bout it?

**Comment by aneyzberg** [comment]
sounds good to me!

**Comment by ultrasaurus** [comment]
@Holyoke @aneyzberg -- it seemed that we only had about 1/3 of the students show up.  @shamus and I wondered if people got confused because the door intercom wasn't working.  Could one of you send a note to folks asking if people had trouble getting in or there was something else that made it difficult to attend?   

Thanks for making this happen!

**Comment by ultrasaurus** [comment]
FYI: created a placeholder for the next event:  https://github.com/railsbridge/organizing/issues/81
sent email to the DevBootcamp folks that @mtvillwock introduced me to
