### ISSUE TITLE
August 21 & 22 SF RailsBridge workshop @ Instacart

### ISSUE THREAD

**Issue by gkop** [railsbridge/organizing#80]
A few months out:
- [x] Find a venue and sponsor for the workshop: Instacart
- [x] Find co-organizers and start going through the workshop cookbook: from Instacart
- [x] Find co-organizers from Railsbridge Volunteers and start going through the workshop cookbook: co-organizers are Gabe and just Gabe :( Anybody want to help me out??

Once we have a venue/sponsor and organizers, we can:
- [x] Set a date  that works for everyone. 
- [x] Set an RSVP limit  that works for everyone
- [x] Post the workshop to Bridge Troll 
- [x] Post the workshop to Meetup if we don't get enough volunteers from BridgeTroll alone. 

One to two weeks out, we can:
- [x] ~~Plan a teacher training, preferably at Instacart, but maybe somewhere else~~ (no teacher training - too small a workshop - and Instacart cannot host anyway
- [x] ~~Order babysitter~~ (no childcare this time)
- [ ] Order breakfast 
- [ ] Order lunch 
- [ ] Find a good place for the afterparty 

After the workshop, we can:
- [ ] Party! 
- [ ] Retro 
- [ ] Expense anything that Instacart doesn't cover

**Comment by sunnyrjuneja** [comment]
@gkop I didn't see it on Bridge Troll. Do you mind posting the link?

**Comment by gkop** [comment]
Sure, https://www.bridgetroll.org/events/186 (it's still unpublished)

**Comment by aneyzberg** [comment]
Great workshop! closing the issue :)
