### ISSUE TITLE
Nov 20 & 21 SF RailsBridge workshop @ HackerOne

### ISSUE THREAD

**Issue by aneyzberg** [railsbridge/organizing#83]
A few months out:
- [x] Find a venue and sponsor for the workshop: HackerOne
- [x] Find co-organizers and start going through the workshop cookbook: from HackerOne
- [ ] Find co-organizers from Railsbridge Volunteers and start going through the workshop cookbook:

Once we have a venue/sponsor and organizers, we can:
- [x] Set a date  that works for everyone. 
- [x] Set an RSVP limit  that works for everyone
- [ ] Post the workshop to Bridge Troll 
- [ ] Post the workshop to Meetup if we don't get enough volunteers from BridgeTroll alone. 

One to two weeks out, we can:
- [ ] ~~Plan a teacher training, preferably at Instacart, but maybe somewhere else~~ (no teacher training - too small a workshop - and Instacart cannot host anyway
- [ ] ~~Order babysitter~~ (no childcare this time)
- [ ] Order breakfast 
- [ ] Order lunch 
- [ ] Find a good place for the afterparty 

After the workshop, we can:
- [ ] Party! 
- [ ] Retro 
- [ ] Expense anything that Instacart doesn't cover

**Comment by sidhene** [comment]
Hi Anna,

What's needed here? I just finished a gig and have time.

**Comment by aneyzberg** [comment]
@sidhene Sorry for the delay on this. I think we have this covered. But am meeting with the organizer manager for this one tonight. so will let you know!

**Comment by aneyzberg** [comment]
@sidhene I apologize, I thought I responded but i guess not :/ We are all set for this event. But will keep you posted about the next one in case you are around!

**Comment by sidhene** [comment]
No worries. I just wanted to make sure that you were set. 
I am taking a few months off, so LMK if you want me for something.

**Comment by aneyzberg** [comment]
Sounds good. Thank you! I definitely will.

**Comment by aneyzberg** [comment]
This went well. And hacker one said they would agree to host again :)
