### ISSUE TITLE
May 20th and 21st SF RailsBridge workshop @Bleacher Report

### ISSUE THREAD

**Issue by kkeppel** [railsbridge/organizing#88]
A few months out:
- [x] Find a venue and sponsor for the workshop: Bleacher Report
- [x]  Find co-organizers and start going through the workshop cookbook: Anna
- [ ]  Find co-organizers from RailsBridge Volunteers and start going through the workshop cookbook:

Once we have a venue/sponsor and organizers, we can:
- [x]  Set a date that works for everyone. May 20-21
- [x]  Set an RSVP limit that works for everyone. 50
- [ ]  Post the workshop to Bridge Troll.
- [ ]  Post the workshop to Meetup if we don't get enough volunteers from BridgeTroll alone.

One to two weeks out, we can:
- [ ]  Order babysitter
- [ ]  Order breakfast
- [ ]  Order lunch
- [ ]  Find a good place for the afterparty

After the workshop, we can:
- [ ]  Party!
- [ ]  Retro
- [ ]  Expense anything that Instacart doesn't cover

**Comment by aneyzberg** [comment]
This was the first time at bleacher report and it was a great venue. Closing this issue.
