### ISSUE TITLE
June 24th and June 25th RailsBridge workshop @ Dev BootCamp

### ISSUE THREAD

**Issue by JasonEb** [railsbridge/organizing#90]
Goals:
- [x] Pick a curriculum (Rails, Ruby)
- [x] Find a venue and sponsor for the workshop.
- [ ] Find two co-organizers. It's a lot of work, but always a lot of fun. No experience is necessary; checkout the [workshop cookbook](https://github.com/railsbridge/docs/wiki/Cookbook) if it's new to you. (Also, we match up first time organizers with mentors.)
- [ ] Read through the [Fundraising and Accounting Docs](https://github.com/railsbridge/docs/wiki/Money-Things)

Leave a comment below if you're able to host, sponsor or organize! :smile_cat: 

Once we have a a venue, sponsors, and organizers, we can:
- [x ] Work together to set an RSVP limit that works for everyone
- [x ] Post the workshop to [Bridge Troll](http://www.bridgetroll.org/)

Two weeks out, we can:
- [ ] Order breakfast
- [ ] Order lunch
- [x] Find a good place for the afterparty

After the workshop, we can:
- [ ] Party! :tada:  
- [ ] Retro

:tulip:

**Comment by aneyzberg** [comment]
This was a great workshop! Closing the issue.
