### ISSUE TITLE
Cleveland Railsbridge Workshop, September 16-17, 2016

### ISSUE THREAD

**Issue by hfenton** [railsbridge/organizing#91]
This workshop's going to be amazing!! Here's what we need to do!

A few months out:
- [x] Decide on a date!! (September 16-17)
- [x]  Find a venue (see http://railsbridge.org/help/host) (Cover My Meds)
- [x]  Find sponsors for the workshop. This workshop covers Rails. Sponsoring the workshop costs between $800 - $1,000, depending on the size of the workshop. (Currently CMM, others welcome)
- [x]  Find two co-organizers. It's a lot of work, but always a lot of fun. No experience is necessary; checkout the workshop cookbook if it's new to you.

Leave a comment below if you're able to host, sponsor or organize! 😸

Once we have a a venue, sponsors, and organizers, we can:
- [x]  Work together to set an RSVP limit that works for everyone (set it to 35 based on last year)
- [x]  Get people to volunteer to teach workshop sessions (need about 8-10)
- [ ]  Find a few people to offer baby-sitting in one of the rooms at the venue
- [x]  Update the website (http://clevelandrailsbridge.org/)
  - [x] Register clevelandrailsbridge.org again
  - [x] Configure http://cle-railsbridge.github.io with the new domain
  - [x] Update after-party location
- [x]  Make posters to hang up in prominent places at local colleges/universities
- [ ]  Contact digital arts and comp sci departments of local colleges/universities to forward announcement email
- [x]  Post the workshop to Bridge Troll (https://www.bridgetroll.org/events/276)
- [x]  Post the workshop to Meetup for publicity

One to two weeks out, we can:
- [x]  Plan a teacher training
- [x]  Order breakfast
- [x]  Order lunch
- [x]  Find a good place for the afterparty
- [x]  Conduct the teacher training

After the workshop, we can:
- [ ]  Party! 🎉
- [ ]  Retro

**Comment by jdantonio** [comment]
- [ ] Get Twitter account info
- [ ] Gain access to info@clevelandrailsbridge.org
- [ ] Register clevelandrailsbridge.org again
  - [ ] Configure http://cle-railsbridge.github.io with the new domain
- [x] Generate opening presentation and post to new web site

**Comment by hfenton** [comment]
The event was a success!
