### ISSUE TITLE
RailsBridge Hackathon

### ISSUE THREAD

**Issue by akanshmurthy** [railsbridge/organizing#94]
Is anyone interested in organizing a RailsBridge hackathon? 

Typical format but perhaps volunteers can help lead each team (1 volunteer/team) and guide students with tasks and the like. We could even preselect projects that we know can be done in a day.

I've heard from numerous students that something new compared to the regular curriculum would be welcome.

cc: @aneyzberg

**Comment by siruguri** [comment]
The 18F folks have had "code pairing" sessions a while ago,  that were
similar to this idea. They had some cool 18F projects to hack on.

Typed on a phone

**Comment by akanshmurthy** [comment]
Cool! @siruguri , is that a potential yes, in terms of interest?

**Comment by siruguri** [comment]
@akanshmurthy I'm in general up for organizing, and have co-organized a few RB (Rails intro) events before. If you want to chat/brainstorm offline sometime, lmk. I live in Oakland, and wfh.

**Comment by aneyzberg** [comment]
@akanshmurthy I think that is a great idea, especially if there is a little more structure than a normal hackathon so that less experiences students could also participate.

**Comment by akanshmurthy** [comment]
@siruguri : awesome! I think I might have a sponsor already so perhaps I'll set up an organizer's meeting soon. 

@aneyzberg : totally!

**Comment by akanshmurthy** [comment]
For those thinking about helping, we just had our first organizational meeting with 7 people (volunteers and/or sponsor representatives) in attendance. We are starting the process of determining the content for the event. Ping me if you want to help or have ideas!

**Comment by akanshmurthy** [comment]
Event was a lot of fun! People enjoyed fixing the broken tests and learning about RSpec as well as APIs related to Twilio, Bitly, and Cloudinary. TAs did a great job of stepping up and helping. And, despite a few hiccups, App Academy did a great job of sponsoring!
